apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ NAME }}
  namespace: {{ NAMESPACE }}
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  # hostPath:
  #   path: /
  #   path: {{ PATH }}
  nfs:
    server: fs-6d72ae36.efs.eu-central-1.amazonaws.com
    path: /
