apiVersion: v1
kind: Service
metadata:
  name: {{ NAME }}
  namespace: {{ NAMESPACE }}
  labels:
    app: {{ NAME }}
spec:
  ports:
    - port: {{ PORT }}
      nodePort: {{ NODE_PORT }}
  selector:
    app: {{ NAME }}
    tier: frontend
  type: LoadBalancer
